api_root_path: /
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
db_connection_str: '**********'
db_name: metadata-store
docs_url: /docs
host: 127.0.0.1
kafka_servers:
- kafka:9092
log_level: info
openapi_url: /openapi.json
port: 8080
resource_deletion_event_type: searchable_resource_deleted
resource_upsertion_event_type: searchable_resource_upserted
searchable_classes:
  Dataset:
    description: Dataset grouping files under controlled access.
    facetable_properties:
    - key: type
      name: Type
    - key: study.type
      name: Study Type
    - key: study.project.alias
      name: Project Alias
searchable_resource_events_topic: searchable_resource_events
service_instance_id: '1'
service_name: mass
workers: 1
