db_connection_str: mongodb://localhost:27017
db_name: metadata-store
searchable_classes:
  Dataset:
    description: Dataset grouping files under controlled access.
    facetable_properties:
      - key: type # a property directly part of the dataset
        name: Type
      - key: "study.type" # a property that is part of study that is embedded into this dataset
        name: Study Type
      - key: "study.project.alias" # a property part of a deeply embedded resource
        name: Project Alias
searchable_resource_events_topic: searchable_resource_events
resource_deletion_event_type: searchable_resource_deleted
resource_upsertion_event_type: searchable_resource_upserted
service_instance_id: 001
kafka_servers: ["kafka:9092"]
