db_connection_str: mongodb://localhost:27017
db_name: metadata-store
searchable_classes:
  Dataset:
    description: Dataset grouping files under controlled access.
    facetable_properties: [
        "type", # a property directly part of the dataset
        "study.type", # a property that is part of study that is embedded into this dataset
        "study.project.alias", # a property part of a deeply embedded resource
      ]
